# Mini Project: Customer Sales Insights

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('superstore.db')
print('Connected to superstore.db successfully.')

Connected to superstore.db successfully.

In [2]:
pd.read_sql("""
SELECT name FROM sqlite_master WHERE type='table'
""", conn)

             name
0  superstore_raw
1       customers
2          orders
3        products

## 1. Top 5 Customers

In [3]:
query1 = """
WITH customer_sales AS
(
    SELECT c.`Customer Name`, SUM(o.Sales) AS Total_Sales
    FROM customers c
    JOIN orders o ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer ID`, c.`Customer Name`
)
SELECT *
FROM customer_sales
ORDER BY Total_Sales DESC
LIMIT 5
"""

pd.read_sql(query1, conn)

   Customer Name  Total_Sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

## 2. Bottom 5 Customers

In [4]:
query2 = """
WITH customer_sales AS
(
    SELECT c.`Customer Name`, SUM(o.Sales) AS Total_Sales
    FROM customers c
    JOIN orders o ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer ID`, c.`Customer Name`
)
SELECT *
FROM customer_sales
ORDER BY Total_Sales ASC
LIMIT 5
"""

pd.read_sql(query2, conn)

     Customer Name  Total_Sales
0    Thais Sissman        4.833
1     Lela Donovan        5.304
2     Carl Jackson       16.520
3  Mitch Gastineau       16.739
4       Roy Skaria       22.328

## 3. Customers With Only One Order

In [5]:
query3 = """
SELECT c.`Customer Name`,
       COUNT(DISTINCT o.`Order ID`) AS Order_Count
FROM customers c
JOIN orders o ON c.`Customer ID` = o.`Customer ID`
GROUP BY c.`Customer ID`, c.`Customer Name`
HAVING COUNT(DISTINCT o.`Order ID`) = 1
"""

pd.read_sql(query3, conn)

        Customer Name  Order_Count
0   Anthony O'Donnell            1
1      Anemone Ratner            1
2        Carl Jackson            1
3        Jenna Caffey            1
4      Jocasta Rupert            1
5        Lela Donovan            1
6     Mitch Gastineau            1
7   Patricia Hirasaki            1
8     Ricardo Emerson            1
9       Roland Murray            1
10  Susan MacKendrick            1
11      Theresa Coyne            1

## 4. Customers With Above Average Sales

In [6]:
query4 = """
WITH customer_sales AS
(
    SELECT c.`Customer Name`, SUM(o.Sales) AS Total_Sales
    FROM customers c
    JOIN orders o ON c.`Customer ID` = o.`Customer ID`
    GROUP BY c.`Customer ID`, c.`Customer Name`
)
SELECT *
FROM customer_sales
WHERE Total_Sales >
(
    SELECT AVG(Total_Sales)
    FROM customer_sales
)
ORDER BY Total_Sales DESC
"""

pd.read_sql(query4, conn)

     Customer Name  Total_Sales
0      Sean Miller    25043.050
1     Tamara Chand    19052.218
2     Raymond Buch    15117.339
3     Tom Ashbrook    14595.620
4    Adrian Barton    14473.571
..             ...          ...
289     Julie Kriz     2932.484
290    Shaun Weien     2921.544
291   Maris LaWare     2921.500
292       Rob Dowd     2912.894
293   Craig Yedwab     2900.026

[294 rows x 2 columns]

## 5. Highest Order Value Per Customer

In [7]:
query5 = """
SELECT c.`Customer Name`,
       MAX(o.Sales) AS Highest_Order_Value
FROM customers c
JOIN orders o ON c.`Customer ID` = o.`Customer ID`
GROUP BY c.`Customer ID`, c.`Customer Name`
ORDER BY Highest_Order_Value DESC
"""

pd.read_sql(query5, conn)

       Customer Name  Highest_Order_Value
0        Sean Miller            22638.480
1       Tamara Chand            17499.950
2       Raymond Buch            13999.960
3       Tom Ashbrook            11199.968
4       Hunter Lopez            10499.970
..               ...                  ...
788     Carl Jackson               16.520
789  Mitch Gastineau               12.320
790       Roy Skaria                9.648
791     Lela Donovan                5.304
792    Thais Sissman                2.808

[793 rows x 2 columns]